name: CD

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js in ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Build
        run: npm run build

      - name: Publish
        run: npm run publish



